# Generated by Django 2.1.1 on 2020-07-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.IntegerField(blank=True, default=1, primary_key=True, serialize=False)),
                ('msg_text', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
