# Generated by Django 2.1.1 on 2020-07-29 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200729_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
